### ISSUE TITLE
Is there a version compatible with Node Versions >= 4.*

### ISSUE THREAD

**Issue by mapfruition** [zhm/node-spatialite#12]
node-spatialite Installs and builds like a champ in node versions 0.12.*.  We were just recently evaluating dependencies in Node v4 and v5 and node-spatialite was the only module unable to install.

Output follows...

In file included from ../src/spatialite/deps/geos/geos/include/geos/geom/Coordinate.inl:22:0,
                 from ../src/spatialite/deps/geos/geos/include/geos/geom/Coordinate.h:158,
                 from ../src/spatialite/deps/geos/geos/include/geos/algorithm/LineIntersector.h:26,
                 from ../src/spatialite/deps/geos/geos/src/algorithm/LineIntersector.cpp:20:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
make: *** [Release/obj.target/geos/src/spatialite/deps/geos/geos/src/algorithm/LineIntersector.o] Error 1
make: Leaving directory `<app-directory>/node_modules/spatialite/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-c9
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/workspace/webapps/pointreports-api/node_modules/spatialite
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "install" "spatialite"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! spatialite@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spatialite@0.0.5 install script 'node-gyp rebuild'.

**Comment by zhm** [comment]
I have a branch with compiled binaries working. It only has x64 linux binaries so far...

```
npm install spatialite@zhm/node-spatialite#binaries --save
```

**Comment by fbm-static** [comment]
I'm experiencing the same. I have node v5.
